// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core;

namespace NotificationHubs.Models
{
    /// <summary> Represents an ADM based Azure Notification Hubs registration description. </summary>
    public partial class AdmRegistrationDescription
    {
        /// <summary> Initializes a new instance of AdmRegistrationDescription. </summary>
        /// <param name="admRegistrationId"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="admRegistrationId"/> is null. </exception>
        public AdmRegistrationDescription(string admRegistrationId)
        {
            Argument.AssertNotNull(admRegistrationId, nameof(admRegistrationId));

            AdmRegistrationId = admRegistrationId;
        }

        public string AdmRegistrationId { get; set; }
    }
}
