// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure;
using Azure.Core;

namespace NotificationHubs.Models
{
    public partial class AdmTemplateRegistrationDescription : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("admRegistrationId");
            writer.WriteStringValue(AdmRegistrationId);
            writer.WritePropertyName("bodyTemplate");
            writer.WriteStringValue(BodyTemplate);
            if (Optional.IsDefined(TemplateName))
            {
                writer.WritePropertyName("templateName");
                writer.WriteStringValue(TemplateName);
            }
            writer.WriteEndObject();
        }

        internal static AdmTemplateRegistrationDescription DeserializeAdmTemplateRegistrationDescription(JsonElement element)
        {
            string admRegistrationId = default;
            string bodyTemplate = default;
            Optional<string> templateName = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("admRegistrationId"))
                {
                    admRegistrationId = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("bodyTemplate"))
                {
                    bodyTemplate = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("templateName"))
                {
                    templateName = property.Value.GetString();
                    continue;
                }
            }
            return new AdmTemplateRegistrationDescription(admRegistrationId, bodyTemplate, templateName);
        }

        internal RequestContent ToRequestContent()
        {
            var content = new Utf8JsonRequestContent();
            content.JsonWriter.WriteObjectValue(this);
            return content;
        }

        internal static AdmTemplateRegistrationDescription FromResponse(Response response)
        {
            using var document = JsonDocument.Parse(response.Content);
            return DeserializeAdmTemplateRegistrationDescription(document.RootElement);
        }
    }
}
