// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure;
using Azure.Core;

namespace NotificationHubs.Models
{
    public partial class AppleRegistrationDescription : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("deviceToken");
            writer.WriteStringValue(DeviceToken);
            writer.WriteEndObject();
        }

        internal static AppleRegistrationDescription DeserializeAppleRegistrationDescription(JsonElement element)
        {
            string deviceToken = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("deviceToken"))
                {
                    deviceToken = property.Value.GetString();
                    continue;
                }
            }
            return new AppleRegistrationDescription(deviceToken);
        }

        internal RequestContent ToRequestContent()
        {
            var content = new Utf8JsonRequestContent();
            content.JsonWriter.WriteObjectValue(this);
            return content;
        }

        internal static AppleRegistrationDescription FromResponse(Response response)
        {
            using var document = JsonDocument.Parse(response.Content);
            return DeserializeAppleRegistrationDescription(document.RootElement);
        }
    }
}
