// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core;

namespace NotificationHubs.Models
{
    /// <summary> Represents an Apple based Azure Notification Hubs registration description. </summary>
    public partial class AppleRegistrationDescription
    {
        /// <summary> Initializes a new instance of AppleRegistrationDescription. </summary>
        /// <param name="deviceToken"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="deviceToken"/> is null. </exception>
        public AppleRegistrationDescription(string deviceToken)
        {
            Argument.AssertNotNull(deviceToken, nameof(deviceToken));

            DeviceToken = deviceToken;
        }

        public string DeviceToken { get; set; }
    }
}
