// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core;

namespace NotificationHubs.Models
{
    /// <summary> Represents a Baidu template based Azure Notification Hubs registration description. </summary>
    public partial class BaiduTemplateRegistrationDescription
    {
        /// <summary> Initializes a new instance of BaiduTemplateRegistrationDescription. </summary>
        /// <param name="baiduChannelId"></param>
        /// <param name="baiduUserId"></param>
        /// <param name="bodyTemplate"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="baiduChannelId"/>, <paramref name="baiduUserId"/> or <paramref name="bodyTemplate"/> is null. </exception>
        public BaiduTemplateRegistrationDescription(string baiduChannelId, string baiduUserId, string bodyTemplate)
        {
            Argument.AssertNotNull(baiduChannelId, nameof(baiduChannelId));
            Argument.AssertNotNull(baiduUserId, nameof(baiduUserId));
            Argument.AssertNotNull(bodyTemplate, nameof(bodyTemplate));

            BaiduChannelId = baiduChannelId;
            BaiduUserId = baiduUserId;
            BodyTemplate = bodyTemplate;
        }
        /// <summary> Initializes a new instance of BaiduTemplateRegistrationDescription. </summary>
        /// <param name="baiduChannelId"></param>
        /// <param name="baiduUserId"></param>
        /// <param name="bodyTemplate"></param>
        /// <param name="templateName"></param>
        internal BaiduTemplateRegistrationDescription(string baiduChannelId, string baiduUserId, string bodyTemplate, string templateName)
        {
            BaiduChannelId = baiduChannelId;
            BaiduUserId = baiduUserId;
            BodyTemplate = bodyTemplate;
            TemplateName = templateName;
        }

        public string BaiduChannelId { get; set; }

        public string BaiduUserId { get; set; }

        public string BodyTemplate { get; set; }

        public string TemplateName { get; set; }
    }
}
