// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure;
using Azure.Core;

namespace NotificationHubs.Models
{
    public partial class BaiduTemplateRegistrationDescription : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("baiduChannelId");
            writer.WriteStringValue(BaiduChannelId);
            writer.WritePropertyName("baiduUserId");
            writer.WriteStringValue(BaiduUserId);
            writer.WritePropertyName("bodyTemplate");
            writer.WriteStringValue(BodyTemplate);
            if (Optional.IsDefined(TemplateName))
            {
                writer.WritePropertyName("templateName");
                writer.WriteStringValue(TemplateName);
            }
            writer.WriteEndObject();
        }

        internal static BaiduTemplateRegistrationDescription DeserializeBaiduTemplateRegistrationDescription(JsonElement element)
        {
            string baiduChannelId = default;
            string baiduUserId = default;
            string bodyTemplate = default;
            Optional<string> templateName = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("baiduChannelId"))
                {
                    baiduChannelId = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("baiduUserId"))
                {
                    baiduUserId = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("bodyTemplate"))
                {
                    bodyTemplate = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("templateName"))
                {
                    templateName = property.Value.GetString();
                    continue;
                }
            }
            return new BaiduTemplateRegistrationDescription(baiduChannelId, baiduUserId, bodyTemplate, templateName);
        }

        internal RequestContent ToRequestContent()
        {
            var content = new Utf8JsonRequestContent();
            content.JsonWriter.WriteObjectValue(this);
            return content;
        }

        internal static BaiduTemplateRegistrationDescription FromResponse(Response response)
        {
            using var document = JsonDocument.Parse(response.Content);
            return DeserializeBaiduTemplateRegistrationDescription(document.RootElement);
        }
    }
}
