// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure;
using Azure.Core;

namespace NotificationHubs.Models
{
    public partial class BaiduRegistrationDescription : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("baiduChannelId");
            writer.WriteStringValue(BaiduChannelId);
            writer.WritePropertyName("baiduUserId");
            writer.WriteStringValue(BaiduUserId);
            writer.WriteEndObject();
        }

        internal static BaiduRegistrationDescription DeserializeBaiduRegistrationDescription(JsonElement element)
        {
            string baiduChannelId = default;
            string baiduUserId = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("baiduChannelId"))
                {
                    baiduChannelId = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("baiduUserId"))
                {
                    baiduUserId = property.Value.GetString();
                    continue;
                }
            }
            return new BaiduRegistrationDescription(baiduChannelId, baiduUserId);
        }

        internal RequestContent ToRequestContent()
        {
            var content = new Utf8JsonRequestContent();
            content.JsonWriter.WriteObjectValue(this);
            return content;
        }

        internal static BaiduRegistrationDescription FromResponse(Response response)
        {
            using var document = JsonDocument.Parse(response.Content);
            return DeserializeBaiduRegistrationDescription(document.RootElement);
        }
    }
}
