// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure;
using Azure.Core;

namespace NotificationHubs.Models
{
    public partial class BrowserPushHandle : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("endpoint");
            writer.WriteStringValue(Endpoint);
            writer.WritePropertyName("p256dh");
            writer.WriteStringValue(P256dh);
            writer.WritePropertyName("auth");
            writer.WriteStringValue(Auth);
            writer.WriteEndObject();
        }

        internal static BrowserPushHandle DeserializeBrowserPushHandle(JsonElement element)
        {
            string endpoint = default;
            string p256dh = default;
            string auth = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("endpoint"))
                {
                    endpoint = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("p256dh"))
                {
                    p256dh = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("auth"))
                {
                    auth = property.Value.GetString();
                    continue;
                }
            }
            return new BrowserPushHandle(endpoint, p256dh, auth);
        }

        internal RequestContent ToRequestContent()
        {
            var content = new Utf8JsonRequestContent();
            content.JsonWriter.WriteObjectValue(this);
            return content;
        }

        internal static BrowserPushHandle FromResponse(Response response)
        {
            using var document = JsonDocument.Parse(response.Content);
            return DeserializeBrowserPushHandle(document.RootElement);
        }
    }
}
