// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure;
using Azure.Core;

namespace NotificationHubs.Models
{
    public partial class BrowserInstallation : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("pushHandle");
            writer.WriteObjectValue(PushHandle);
            writer.WriteEndObject();
        }

        internal static BrowserInstallation DeserializeBrowserInstallation(JsonElement element)
        {
            BrowserPushHandle pushHandle = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("pushHandle"))
                {
                    pushHandle = BrowserPushHandle.DeserializeBrowserPushHandle(property.Value);
                    continue;
                }
            }
            return new BrowserInstallation(pushHandle);
        }

        internal RequestContent ToRequestContent()
        {
            var content = new Utf8JsonRequestContent();
            content.JsonWriter.WriteObjectValue(this);
            return content;
        }

        internal static BrowserInstallation FromResponse(Response response)
        {
            using var document = JsonDocument.Parse(response.Content);
            return DeserializeBrowserInstallation(document.RootElement);
        }
    }
}
