// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core;

namespace NotificationHubs.Models
{
    /// <summary> Represents a Web Push push handle. </summary>
    public partial class BrowserPushHandle
    {
        /// <summary> Initializes a new instance of BrowserPushHandle. </summary>
        /// <param name="endpoint"></param>
        /// <param name="p256dh"></param>
        /// <param name="auth"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="endpoint"/>, <paramref name="p256dh"/> or <paramref name="auth"/> is null. </exception>
        public BrowserPushHandle(string endpoint, string p256dh, string auth)
        {
            Argument.AssertNotNull(endpoint, nameof(endpoint));
            Argument.AssertNotNull(p256dh, nameof(p256dh));
            Argument.AssertNotNull(auth, nameof(auth));

            Endpoint = endpoint;
            P256dh = p256dh;
            Auth = auth;
        }

        public string Endpoint { get; set; }

        public string P256dh { get; set; }

        public string Auth { get; set; }
    }
}
