// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core;

namespace NotificationHubs.Models
{
    /// <summary> Represents an Web Push based Azure Notification Hubs Installation. </summary>
    public partial class BrowserInstallation
    {
        /// <summary> Initializes a new instance of BrowserInstallation. </summary>
        /// <param name="pushHandle"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="pushHandle"/> is null. </exception>
        public BrowserInstallation(BrowserPushHandle pushHandle)
        {
            Argument.AssertNotNull(pushHandle, nameof(pushHandle));

            PushHandle = pushHandle;
        }

        public BrowserPushHandle PushHandle { get; set; }
    }
}
