// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure;
using Azure.Core;

namespace NotificationHubs.Models
{
    public partial class BrowserTemplateRegistrationDescription : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("endpoint");
            writer.WriteStringValue(Endpoint);
            writer.WritePropertyName("auth");
            writer.WriteStringValue(Auth);
            writer.WritePropertyName("p256dh");
            writer.WriteStringValue(P256dh);
            writer.WritePropertyName("bodyTemplate");
            writer.WriteStringValue(BodyTemplate);
            if (Optional.IsDefined(TemplateName))
            {
                writer.WritePropertyName("templateName");
                writer.WriteStringValue(TemplateName);
            }
            writer.WriteEndObject();
        }

        internal static BrowserTemplateRegistrationDescription DeserializeBrowserTemplateRegistrationDescription(JsonElement element)
        {
            string endpoint = default;
            string auth = default;
            string p256dh = default;
            string bodyTemplate = default;
            Optional<string> templateName = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("endpoint"))
                {
                    endpoint = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("auth"))
                {
                    auth = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("p256dh"))
                {
                    p256dh = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("bodyTemplate"))
                {
                    bodyTemplate = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("templateName"))
                {
                    templateName = property.Value.GetString();
                    continue;
                }
            }
            return new BrowserTemplateRegistrationDescription(endpoint, auth, p256dh, bodyTemplate, templateName);
        }

        internal RequestContent ToRequestContent()
        {
            var content = new Utf8JsonRequestContent();
            content.JsonWriter.WriteObjectValue(this);
            return content;
        }

        internal static BrowserTemplateRegistrationDescription FromResponse(Response response)
        {
            using var document = JsonDocument.Parse(response.Content);
            return DeserializeBrowserTemplateRegistrationDescription(document.RootElement);
        }
    }
}
