// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure;
using Azure.Core;

namespace NotificationHubs.Models
{
    public partial class GcmRegistrationDescription : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("gcmRegistrationId");
            writer.WriteStringValue(GcmRegistrationId);
            writer.WriteEndObject();
        }

        internal static GcmRegistrationDescription DeserializeGcmRegistrationDescription(JsonElement element)
        {
            string gcmRegistrationId = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("gcmRegistrationId"))
                {
                    gcmRegistrationId = property.Value.GetString();
                    continue;
                }
            }
            return new GcmRegistrationDescription(gcmRegistrationId);
        }

        internal RequestContent ToRequestContent()
        {
            var content = new Utf8JsonRequestContent();
            content.JsonWriter.WriteObjectValue(this);
            return content;
        }

        internal static GcmRegistrationDescription FromResponse(Response response)
        {
            using var document = JsonDocument.Parse(response.Content);
            return DeserializeGcmRegistrationDescription(document.RootElement);
        }
    }
}
