// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;
using Azure.Core;

namespace NotificationHubs.Models
{
    /// <summary> Represents an Azure Notification Hubs Installation. </summary>
    public partial class Installation
    {
        /// <summary> Initializes a new instance of Installation. </summary>
        /// <param name="installationId"></param>
        /// <param name="tags"></param>
        /// <param name="templates"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="installationId"/>, <paramref name="tags"/> or <paramref name="templates"/> is null. </exception>
        public Installation(string installationId, IEnumerable<string> tags, IDictionary<string, string> templates)
        {
            Argument.AssertNotNull(installationId, nameof(installationId));
            Argument.AssertNotNull(tags, nameof(tags));
            Argument.AssertNotNull(templates, nameof(templates));

            InstallationId = installationId;
            Tags = tags.ToList();
            Templates = templates;
        }
        /// <summary> Initializes a new instance of Installation. </summary>
        /// <param name="installationId"></param>
        /// <param name="userId"></param>
        /// <param name="expirationTime"></param>
        /// <param name="lastUpdate"></param>
        /// <param name="tags"></param>
        /// <param name="templates"></param>
        internal Installation(string installationId, string userId, string expirationTime, string lastUpdate, IList<string> tags, IDictionary<string, string> templates)
        {
            InstallationId = installationId;
            UserId = userId;
            ExpirationTime = expirationTime;
            LastUpdate = lastUpdate;
            Tags = tags;
            Templates = templates;
        }

        public string InstallationId { get; set; }

        public string UserId { get; set; }

        public string ExpirationTime { get; }

        public string LastUpdate { get; }

        public IList<string> Tags { get; }

        public IDictionary<string, string> Templates { get; }
    }
}
