// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Azure.Core;

namespace NotificationHubs.Models
{
    /// <summary> Represents a Windows Phone template based Azure Notification Hubs registration description. </summary>
    public partial class MpnsTemplateRegistrationDescription
    {
        /// <summary> Initializes a new instance of MpnsTemplateRegistrationDescription. </summary>
        /// <param name="channelUri"></param>
        /// <param name="bodyTemplate"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="channelUri"/> or <paramref name="bodyTemplate"/> is null. </exception>
        public MpnsTemplateRegistrationDescription(string channelUri, string bodyTemplate)
        {
            Argument.AssertNotNull(channelUri, nameof(channelUri));
            Argument.AssertNotNull(bodyTemplate, nameof(bodyTemplate));

            ChannelUri = channelUri;
            BodyTemplate = bodyTemplate;
            MpnsHeaders = new ChangeTrackingDictionary<string, string>();
        }
        /// <summary> Initializes a new instance of MpnsTemplateRegistrationDescription. </summary>
        /// <param name="channelUri"></param>
        /// <param name="bodyTemplate"></param>
        /// <param name="templateName"></param>
        /// <param name="mpnsHeaders"></param>
        internal MpnsTemplateRegistrationDescription(string channelUri, string bodyTemplate, string templateName, IDictionary<string, string> mpnsHeaders)
        {
            ChannelUri = channelUri;
            BodyTemplate = bodyTemplate;
            TemplateName = templateName;
            MpnsHeaders = mpnsHeaders;
        }

        public string ChannelUri { get; set; }

        public string BodyTemplate { get; set; }

        public string TemplateName { get; set; }

        public IDictionary<string, string> MpnsHeaders { get; }
    }
}
