// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core;

namespace NotificationHubs.Models
{
    /// <summary> Represents a Windows Phone based Azure Notification Hubs registration description. </summary>
    public partial class MpnsRegistrationDescription
    {
        /// <summary> Initializes a new instance of MpnsRegistrationDescription. </summary>
        /// <param name="channelUri"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="channelUri"/> is null. </exception>
        public MpnsRegistrationDescription(string channelUri)
        {
            Argument.AssertNotNull(channelUri, nameof(channelUri));

            ChannelUri = channelUri;
        }

        public string ChannelUri { get; set; }
    }
}
